# Generated by Django 3.1.7 on 2021-03-25 05:39

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='email address')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='(Note: Contact Number, help us to contact you soon and it is optional)', max_length=13, null=True, region=None, unique=True, verbose_name='contact number')),
                ('college_id_number', models.CharField(max_length=20, unique=True, verbose_name='college roll number')),
                ('college', models.CharField(max_length=150, verbose_name='college')),
                ('department', models.CharField(max_length=60, verbose_name='department')),
                ('course', models.CharField(max_length=20, verbose_name='course')),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=3, verbose_name='year')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
