# Generated by Django 3.1.7 on 2021-03-25 05:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='event name')),
                ('description', models.TextField(verbose_name='event description')),
                ('tags', models.TextField(help_text='seperate the tags with a ","', verbose_name='event tags')),
                ('levels', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='total levels in the event')),
                ('date', models.DateField(verbose_name='date of event')),
                ('location', models.CharField(max_length=100, verbose_name='location of the event')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='created on')),
                ('for_staff', models.BooleanField(default=False, verbose_name='message for staff?')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
    ]
