# Generated by Django 3.1.7 on 2021-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
