# Generated by Django 3.1.7 on 2021-03-28 06:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(validators=[core.models.Event.date_validator], verbose_name='date of event'),
        ),
    ]
