# Generated by Django 3.1.7 on 2021-03-28 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210328_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='head_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='instructions',
            field=models.TextField(help_text='Instructions for the participants', null=True, verbose_name='instructions'),
        ),
        migrations.AddField(
            model_name='event',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='quote'),
        ),
        migrations.AddField(
            model_name='event',
            name='slogan',
            field=models.TextField(blank=True, null=True, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact Number is optional', max_length=13, null=True, region=None, unique=True, verbose_name='contact number'),
        ),
    ]
