# Generated by Django 3.1.7 on 2021-03-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210328_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(null=True, verbose_name='Starting Time of event'),
        ),
    ]
