# Generated by Django 3.1.7 on 2021-03-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='url value field for events', null=True, unique=True),
        ),
    ]
