# Generated by Django 3.1.7 on 2021-04-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210402_1107'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team',
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to='core.Team'),
        ),
    ]
