# Generated by Django 3.1.7 on 2021-04-02 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210402_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team',
        ),
        migrations.AddField(
            model_name='event',
            name='team_members',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='team members'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
