# Generated by Django 3.1.7 on 2021-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210402_1551'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_user1',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('team_name', 'user'), name='unique_team_user'),
        ),
    ]
