# Generated by Django 3.1.7 on 2021-04-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210402_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
