# Generated by Django 3.1.7 on 2021-04-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210402_2130'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team',
        ),
    ]
