# Generated by Django 3.1.7 on 2021-04-02 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210402_2132'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_event_user',
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_user',
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_event_user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('team_name', 'event'), name='unique_team_event'),
        ),
    ]
