# Generated by Django 3.1.7 on 2021-04-04 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210403_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='levels_cleared',
            field=models.PositiveIntegerField(default=0, verbose_name='levels cleared'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(help_text='Team name must be unique (case-sensitive)', max_length=25),
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Enter the winning position of the participant or team', max_length=10, verbose_name='winning position')),
                ('event', models.ForeignKey(help_text='Choose the event in which they won', on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('team', models.ForeignKey(blank=True, help_text='If the winner is a group of participant, choose the team from here', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('user', models.ForeignKey(blank=True, help_text='If the winner is a single participant, choose the user from here', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'winner',
                'verbose_name_plural': 'winner',
            },
        ),
    ]
