# Generated by Django 3.1.7 on 2021-04-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210405_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winner',
            options={'verbose_name': 'winner', 'verbose_name_plural': 'winners'},
        ),
    ]
