# Generated by Django 3.1.7 on 2021-04-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210405_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='levels_cleared',
        ),
        migrations.AddField(
            model_name='team',
            name='current_level',
            field=models.PositiveIntegerField(default=0, verbose_name='current level'),
        ),
    ]
