# Generated by Django 3.1.7 on 2021-04-05 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210405_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, to='core.Event'),
        ),
    ]
