# Generated by Django 3.1.7 on 2021-04-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_event_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='user',
        ),
    ]
