"""
Django settings for eventia project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$8!12bd1v32qrvz)@!zet(#ea$sd%_-crp#9xf5(vwg21m72u3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'core',
	'crispy_forms',
	'phonenumber_field',
	'django_email_verification',
	'django_extensions',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eventia.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'eventia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': BASE_DIR / 'db.sqlite3',
	}
}

# DATABASES = {
#      'default': {
#          'ENGINE': 'django.db.backends.postgresql_psycopg2',
#          'NAME': 'ddb3a5n79ritlp',
#          'USER': 'ppmjpaxgydscti',
#          'PASSWORD': 'e1ea1c3224079c6d993dee0b5acb3e26a48ec5ac0e18e2dd77703a72a43398e1',
#          'HOST': 'ec2-52-45-73-150.compute-1.amazonaws.com',
#          'PORT': '5432',

#      }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = 'static'
STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom User Model
AUTH_USER_MODEL = 'core.User'

LOGIN_REDIRECT_URL='/dashboard/'
LOGIN_URL='/login/'
LOGOUT_REDIRECT_URL='/login/'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 5
SESSION_SAVE_EVERY_REQUEST = True

PASSWORD_RESET_TIMEOUT = 300

# Default country from phone field
PHONENUMBER_DB_FORMAT = 'E164'
PHONENUMBER_DEFAULT_REGION = 'IN'

# Mail Server
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp-relay.sendinblue.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
# EMAIL_HOST_USER = 'revanthlp3@gmail.com'
EMAIL_HOST_USER = '18x039@psgtech.ac.in'
# EMAIL_HOST_PASSWORD = 'xsmtpsib-d4324efcc9639992ea38695c4739ae9800faa29fe6c68364c34a91c0c588991e-kPQNW9cR2KFIDdtM'
EMAIL_HOST_PASSWORD = 'Pikamarsh@rath'
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = '18x039@psgtech.ac.in'

def verified_callback(user):
	user.is_active = True

EMAIL_VERIFIED_CALLBACK = verified_callback
# EMAIL_SERVER = 'smtp-relay.sendinblue.com'
EMAIL_SERVER = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_ADDRESS = 'revanthlp3@gmail.com'
EMAIL_ADDRESS = '18x039@psgtech.ac.in'
# EMAIL_FROM_ADDRESS = 'revanthlp3@gmail.com'
EMAIL_FROM_ADDRESS = '18x039@psgtech.ac.in'
# EMAIL_PASSWORD = 'xsmtpsib-d4324efcc9639992ea38695c4739ae9800faa29fe6c68364c34a91c0c588991e-kPQNW9cR2KFIDdtM'
EMAIL_PASSWORD = 'Pikamarsh@rath'
EMAIL_MAIL_SUBJECT = 'Confirm your email'
EMAIL_MAIL_HTML = 'mail_body.html'
EMAIL_PAGE_TEMPLATE = 'confirm_template.html'
EMAIL_MAIL_PLAIN = 'mail_body.txt'
EMAIL_PAGE_DOMAIN = 'https://rathgamer.pythonanywhere.com/'
EMAIL_TOKEN_LIFE = 60 * 5

GRAPH_MODELS = {
	'all_applications':True,
	'group_models':True,
}

import django_heroku
django_heroku.settings(locals())